// T111 record-scope preserve fixture.  Every shape below is required by the task
// contract:
//
//   * one struct record without complete binding evidence living in the same
//     core group as several fully proven struct records, so that preserving the
//     unproven one must not zero the group;
//   * the two production member-access shapes that only exist inside a macro
//     argument -- a nested member with a bit select and a member with a part
//     select -- reproducing the residual StCache root causes;
//   * one macro body expanded twice so that two records claim a single physical
//     range and `macro_origin_conflict` still applies per object;
//   * a Yosys-readable formal cone, which is formal_cone.sv.

`include "t111_macros.svh"

interface t111_if;
    logic       req;
    logic       ack;
    logic [3:0] tag;
    modport Master (output req, input ack, input tag);
    modport Slave  (input req, output ack, output tag);
endinterface

// A named aggregate reached only as a variable or port type, which the product
// does bind, so its alias and its fields are fully proven records.
typedef struct packed {
    logic [3:0] cmd;
    logic       ok;
} t111_inner_t;

// The nested aggregate is anonymous on purpose.  A named typedef used as a
// struct *member* type is a `NamedType` reference, which T111 section 3 does not
// bind, so nesting the aggregate above by name here would rename its declaration
// while leaving that reference untouched.  See the task record: that is a
// pre-existing hole, reproduced separately, and deliberately not exercised here.
typedef struct packed {
    struct packed {
        logic [3:0] cmd;
        logic       ok;
    } inner;
    logic [7:0] wide;
    logic       ok;
} t111_word_t;

// The single member of this aggregate is generated by a macro, so it has no
// source-backed physical declaration and this alias is the only struct record
// here without complete binding evidence.  The macro field is deliberately the
// whole aggregate: no field record is created, so exactly one record -- this
// alias -- must end up preserved.
typedef struct packed {
    `T111_FIELD(macro_field);
} t111_macro_struct_t;

module t111_macro_member (
    input  t111_word_t  pkt,
    input  t111_inner_t blk,
    output logic        chk_nest,
    output logic        chk_bit,
    output logic        chk_part
);
    // The residual production shapes.  A trailing select drops the typed syntax
    // link, so only the expression's own source range can reach the member
    // token; inside a macro argument both ends of that range are macro
    // locations, so they must first be restored to the physical call site.  The
    // second check is the StCache root-cause token type itself: a FieldSymbol of
    // a named aggregate reached with a bit select from inside a macro argument.
    // No identifier of this design is written in any comment, so a byte search
    // for one finds only real code.
    `T111_CHECK(chk_nest, pkt.inner.cmd[1]);
    `T111_CHECK(chk_bit,  blk.cmd[1]);
    `T111_CHECK(chk_part, (^pkt.wide[6:5]));
endmodule

// The same aggregates dereferenced without any macro, so the group carries
// plainly proven struct records next to the unproven one.
module t111_struct_user (
    input  logic [3:0] cmd_i,
    input  logic       ok_i,
    output logic       bit_o,
    output logic [3:0] part_o
);
    t111_word_t  word;
    t111_inner_t plain;
    always_comb begin
        word           = '0;
        word.inner.cmd = cmd_i;
        word.inner.ok  = ok_i;
        word.wide      = {cmd_i, 4'h5};
        word.ok        = ok_i;
        plain.cmd      = cmd_i;
        plain.ok       = ok_i;
    end
    assign bit_o  = word.wide[2] ^ word.ok ^ plain.ok ^ word.inner.ok;
    assign part_o = word.wide[7:4] ^ word.inner.cmd ^ plain.cmd;
endmodule

// The unproven aggregate is really used, so its alias is a genuine rename
// candidate inside the top closure rather than an out-of-closure record.
module t111_macro_struct_user (
    input  logic drive_i,
    output logic out_bit
);
    t111_macro_struct_t macro_word;
    always_comb macro_word.macro_field = drive_i;
    assign out_bit = macro_word.macro_field;
endmodule

// Two expansions of one macro body.  The assigned signal name is written once
// physically, inside the macro header file, but names a different declaration in
// each module below, so one physical range carries two semantic meanings.
module t111_conflict_a (
    input  logic data_i,
    output logic data_o
);
    logic t111_shared_body;
    `T111_BODY_ASSIGN(data_i);
    assign data_o = t111_shared_body;
endmodule

module t111_conflict_b (
    input  logic data_i,
    output logic data_o
);
    logic t111_shared_body;
    `T111_BODY_ASSIGN(data_i);
    assign data_o = t111_shared_body;
endmodule

module t111_if_user (
    t111_if            plain_port,
    input  logic       drive_i,
    input  logic [3:0] tag_i,
    output logic       out_bit
);
    assign plain_port.req = drive_i;
    assign plain_port.ack = drive_i;
    assign plain_port.tag = tag_i;
    assign out_bit = plain_port.req ^ plain_port.ack ^ (plain_port.tag != 4'h0);
endmodule

module t111_mp_user (
    t111_if.Master mp_port,
    output logic   out_bit
);
    assign out_bit = 1'b1;
endmodule

module t111_top (
    input  logic       clk,
    input  logic       in_a,
    input  logic       in_b,
    input  logic [3:0] in_cmd,
    output logic       out_y,
    output logic       out_chk,
    output logic       out_bit,
    output logic [3:0] out_part,
    output logic       out_macro,
    output logic       out_conflict,
    output logic       out_if
);
    t111_if     bus0();
    t111_if     bus1();
    t111_word_t pkt;
    t111_inner_t blk;
    logic       chk_nest;
    logic       chk_bit;
    logic       chk_part;
    logic       conflict_a_o;
    logic       conflict_b_o;
    logic       if_bit;
    logic       mp_bit;

    always_comb begin
        pkt           = '0;
        pkt.inner.cmd = in_cmd;
        pkt.inner.ok  = in_a;
        pkt.wide      = {in_cmd, 4'hA};
        pkt.ok        = in_a;
        blk.cmd       = in_cmd;
        blk.ok        = in_b;
    end

    t111_formal_top u_formal (
        .clk(clk),
        .in_a(in_a),
        .in_b(in_b),
        .out_y(out_y)
    );

    t111_macro_member u_macro_member (
        .pkt(pkt),
        .blk(blk),
        .chk_nest(chk_nest),
        .chk_bit(chk_bit),
        .chk_part(chk_part)
    );

    t111_struct_user u_struct (
        .cmd_i(in_cmd),
        .ok_i(in_a),
        .bit_o(out_bit),
        .part_o(out_part)
    );

    t111_macro_struct_user u_macro_struct (
        .drive_i(in_b),
        .out_bit(out_macro)
    );

    t111_conflict_a u_conflict_a (.data_i(in_a), .data_o(conflict_a_o));
    t111_conflict_b u_conflict_b (.data_i(in_b), .data_o(conflict_b_o));

    t111_if_user u_if_user (
        .plain_port(bus0),
        .drive_i(in_a),
        .tag_i(in_cmd),
        .out_bit(if_bit)
    );

    t111_mp_user u_mp_user (
        .mp_port(bus1),
        .out_bit(mp_bit)
    );

    assign out_chk      = chk_nest ^ chk_bit ^ chk_part;
    assign out_conflict = conflict_a_o ^ conflict_b_o;
    assign out_if       = if_bit ^ mp_bit;
endmodule
