"""SystemVerilog identifier rules used by the mapping vNext boundary."""

from __future__ import annotations

import re
import secrets
import string


# IEEE 1800 reserved words.  Keep this independent from the legacy inventory
# implementation: this module is the small, public naming contract for the
# refactor pipeline.
SYSTEMVERILOG_KEYWORDS: frozenset[str] = frozenset(
    {
        "accept_on",
        "alias",
        "always",
        "always_comb",
        "always_ff",
        "always_latch",
        "and",
        "assert",
        "assign",
        "assume",
        "automatic",
        "before",
        "begin",
        "bind",
        "binsof",
        "bins",
        "bit",
        "break",
        "buf",
        "bufif0",
        "bufif1",
        "byte",
        "case",
        "casex",
        "casez",
        "cell",
        "chandle",
        "checker",
        "class",
        "clocking",
        "cmos",
        "const",
        "constraint",
        "context",
        "continue",
        "config",
        "cover",
        "covergroup",
        "coverpoint",
        "cross",
        "deassign",
        "default",
        "defparam",
        "design",
        "disable",
        "dist",
        "do",
        "edge",
        "else",
        "end",
        "endchecker",
        "endclass",
        "endclocking",
        "endcase",
        "endconfig",
        "endfunction",
        "endgenerate",
        "endgroup",
        "endinterface",
        "endmodule",
        "endpackage",
        "endprimitive",
        "endprogram",
        "endproperty",
        "endsequence",
        "endspecify",
        "endtable",
        "endtask",
        "enum",
        "event",
        "eventually",
        "expect",
        "export",
        "extends",
        "extern",
        "final",
        "first_match",
        "for",
        "force",
        "foreach",
        "forever",
        "fork",
        "forkjoin",
        "function",
        "generate",
        "genvar",
        "global",
        "highz0",
        "highz1",
        "if",
        "iff",
        "ifnone",
        "ignore_bins",
        "illegal_bins",
        "implements",
        "implies",
        "import",
        "incdir",
        "include",
        "instance",
        "initial",
        "inout",
        "input",
        "inside",
        "int",
        "integer",
        "interconnect",
        "interface",
        "intersect",
        "join",
        "join_any",
        "join_none",
        "large",
        "let",
        "liblist",
        "library",
        "local",
        "localparam",
        "logic",
        "longint",
        "macromodule",
        "matches",
        "medium",
        "modport",
        "module",
        "nand",
        "negedge",
        "nettype",
        "new",
        "nexttime",
        "nmos",
        "nor",
        "noshowcancelled",
        "not",
        "notif0",
        "notif1",
        "null",
        "or",
        "output",
        "package",
        "packed",
        "parameter",
        "pmos",
        "posedge",
        "primitive",
        "priority",
        "program",
        "protected",
        "property",
        "pull0",
        "pull1",
        "pulldown",
        "pullup",
        "pulsestyle_ondetect",
        "pulsestyle_onevent",
        "pure",
        "rand",
        "randc",
        "randcase",
        "randsequence",
        "rcmos",
        "real",
        "realtime",
        "ref",
        "reg",
        "reject_on",
        "release",
        "repeat",
        "restrict",
        "return",
        "rnmos",
        "rpmos",
        "rtran",
        "rtranif0",
        "rtranif1",
        "s_always",
        "s_eventually",
        "s_nexttime",
        "s_until",
        "s_until_with",
        "scalared",
        "sequence",
        "shortint",
        "shortreal",
        "showcancelled",
        "signed",
        "small",
        "soft",
        "solve",
        "specify",
        "specparam",
        "static",
        "string",
        "strong",
        "strong0",
        "strong1",
        "struct",
        "super",
        "supply0",
        "supply1",
        "sync_accept_on",
        "sync_reject_on",
        "table",
        "tagged",
        "task",
        "this",
        "throughout",
        "time",
        "timeprecision",
        "timeunit",
        "tran",
        "tranif0",
        "tranif1",
        "tri",
        "tri0",
        "tri1",
        "triand",
        "trior",
        "trireg",
        "type",
        "typedef",
        "union",
        "unique",
        "unique0",
        "unsigned",
        "until",
        "until_with",
        "untyped",
        "use",
        "uwire",
        "var",
        "vectored",
        "virtual",
        "void",
        "wait",
        "wait_order",
        "wand",
        "weak",
        "weak0",
        "weak1",
        "while",
        "wildcard",
        "wire",
        "with",
        "within",
        "wor",
        "xnor",
        "xor",
    }
)


_PLAIN_IDENTIFIER = re.compile(r"[A-Za-z][A-Za-z0-9_]*\Z")


def is_plain_identifier(value: object) -> bool:
    """Return whether *value* is a non-keyword ASCII SystemVerilog name."""

    return (
        isinstance(value, str)
        and _PLAIN_IDENTIFIER.fullmatch(value) is not None
        and value not in SYSTEMVERILOG_KEYWORDS
    )


def secure_name_factory(
    symbol_id: str,
    name_length: int,
    unavailable: frozenset[str],
) -> str:
    """Return a cryptographically unpredictable, collision-free identifier."""

    del symbol_id
    if type(name_length) is not int or name_length < 1:
        raise RuntimeError("name_length cannot produce a plain identifier")
    first_alphabet = string.ascii_letters
    rest_alphabet = string.ascii_letters + string.digits + "_"
    for _ in range(1000):
        candidate = secrets.choice(first_alphabet) + "".join(
            secrets.choice(rest_alphabet) for _ in range(name_length - 1)
        )
        if is_plain_identifier(candidate) and candidate not in unavailable:
            return candidate
    raise RuntimeError("secure name factory exhausted its collision budget")
